remote_theme: "BlackrockDigital/startbootstrap-clean-blog-jekyll"
title: A chat with TARS - Natural Language Understanding
description: A timid journey through the advancements in Natural Language Processing
layout: default
collections:
  authors:
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
defaults:
  - scope:
      path: ""
    values:
      layout: default

#theme: jekyll-theme-cayman
