theme: jekyll-theme-cayman
title: A chat with TARS - Natural Language Understanding
description: A timid journey through the advancements in Natural Language Processing
layout: default
collections:
  authors:

defaults:
  -
  - scope:
      path: "" # Means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
